services:
  react-native:
    container_name: react-container
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - /dev/bus/usb:/dev/bus/usb  # Mount the USB devicess
      - .:/app
    # devices:
    #   - /dev/serial/by-id/usb-SAMSUNG_SAMSUNG_Android_RRCT701KELL-if01:/dev/ttyACM0 # see list usb connect: ls -l /dev/serial/by-id
    stdin_open: true
    tty: true
    # network_mode: host
    networks:
      - my-network

  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android-container
    privileged: true
    ports:
      - "6080:6080"   # Web UI
      - "5554:5554"   # ADB port
      - "5555:5555"   # Emulator port
      - "4723:4723"   # Emulator port
    devices:
      - "/dev/kvm:/dev/kvm"  # Grant access to /dev/kvm
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    tty: true
    networks:
      - my-network

networks:
  my-network:
    driver: bridge